export const CartActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  CHANGE_QUANTITY: "CHANGE_QUANTITY",
  SET_USER_NAME: "SET_USER_NAME",
  SET_USER_ADDRESS: "SET_USER_ADDRESS",
  SET_USER_EMAIL: "SET_USER_EMAIL",
  SET_USER_PHONE: "SET_USER_PHONE",
};
